# host: "18.229.102.98" 
# database: "geoalert_mel"
# user: "postgres" 
# password: "admPostgress2017_7766"
# port: 7766

host: "192.168.4.2" 
database: "geoalert_mel_gav"
user : "postgres" 
password : "postgres"
port : 5434

Url_local : "http://127.0.0.1:5000/"
Url_server : "http://161.0.162.4/"